// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rouafqhhwjzrluljsgch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvdWFmcWhod2p6cmx1bGpzZ2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTA1NzcsImV4cCI6MjA2MzY4NjU3N30.1izKwxBH3LmEGNUn3d8fsjgs96aCH5WfNYzo_ra12mE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);